---

namespace: adfinis
name: semaphoreui
version: 0.1.0
readme: README.md

authors:
  - Patrick Hasler <patrick.hasler@adfinis.com
  - Sebastian Philipp <sebastian.philipp@adfinis.com
  - Samuel Hierholzer <samuel.hierholzer@adfinis.com>

description: >-
  Ansible Collection to setup and manage Semaphore UI in Docker

license:
  - GPL-3.0-or-later

tags:
  - linux
  - infrastructure
  - semaphore
  - semaphoreui

dependencies:
  "community.docker": "*" # latest

repository: https://github.com/adfinis/ansible-collection-semaphoreui
documentation: https://github.com/adfinis/ansible-collection-semaphoreui/README.md
issues: https://github.com/adfinis/ansible-collection-semaphoreui/issues
homepage: https://adfinis.com

build_ignore: []
